### ISSUE TITLE
Python script error

### ISSUE THREAD

**Issue by nightfever77** [yo-han/Home-Assistant-Carelink#73]
Please help:
I am getting a lot of errors when running the script. How should I deal with that?

```
PS C:\Users\night> python carelink_carepartner_api_login.py
  File "C:\Users\night\carelink_carepartner_api_login.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```
Re-downloaded and re-run:

```
PS C:\Users\night> python carelink_carepartner_api_login.py
Traceback (most recent call last):
  File "C:\Users\night\carelink_carepartner_api_login.py", line 49, in <module>
    from seleniumwire import webdriver
  File "C:\Users\night\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\seleniumwire\webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "C:\Users\night\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\seleniumwire\backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "C:\Users\night\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\seleniumwire\server.py", line 5, in <module>
    from seleniumwire.handler import InterceptRequestHandler
  File "C:\Users\night\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\seleniumwire\handler.py", line 5, in <module>
    from seleniumwire import har
  File "C:\Users\night\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\seleniumwire\har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "C:\Users\night\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\seleniumwire\thirdparty\mitmproxy\connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "C:\Users\night\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\seleniumwire\thirdparty\mitmproxy\net\tls.py", line 17, in <module>
    from seleniumwire.thirdparty.mitmproxy.contrib.kaitaistruct import tls_client_hello
  File "C:\Users\night\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\seleniumwire\thirdparty\mitmproxy\contrib\kaitaistruct\tls_client_hello.py", line 10, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by nightfever77** [comment]
After installing these two more packages the script run through. Please update your instuctions with 
pip install setuptools
pip install packaging

**Comment by yo-han** [comment]
#81
