### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ggocsei** [yo-han/Home-Assistant-Carelink#91]
Hi all,

 We get this error after install and setup:

Unexpected error fetching carelink data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/carelink/__init__.py", line 161, in _async_update_data
    recent_data = await self.client.get_recent_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/carelink/api.py", line 390, in get_recent_data
    if self.__session_user["role"]
       ~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

What should be the problem? 

Thanks,
 Gábor

**Comment by yo-han** [comment]
It seems there is no user session when checking for the role of the account. I made a small change to log an error when this happens instead of crashing. Maybe this helps.

**Comment by ggocsei** [comment]
Thanks. The error is gone away, but got new:
/config/custom_components/carelink/__init__.py:88: SyntaxWarning: invalid escape sequence '\.' date_iso = re.sub("\.\d{3}Z$", "+00:00", date)

**Comment by yo-han** [comment]
This is just a syntax warning and nothing that should break the app. I will fix it still, because not exactly what you would like.

**Comment by ggocsei** [comment]
I'd like to connect my device and get the data :smile: 
It's connecting, but is see unknow state on every sensor.  Now only this relevant warning shows up in the log:

Detected blocking call to open with args ('custom_components/carelink/logindata.json', 'r') inside the event loop by custom integration 'carelink' at custom_components/carelink/api.py, line 406: token_data = json.loads(open(filename, "r").read()) (offender: /config/custom_components/carelink/api.py, line 406: token_data = json.loads(open(filename, "r").read()))
